/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class enet_ENetPacketHelper */

#ifndef _Included_enet_ENetPacketHelper
#define _Included_enet_ENetPacketHelper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     enet_ENetPacketHelper
 * Method:    getPacketData
 * Signature: (Lenet/ENetPacket;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_enet_ENetPacketHelper_getPacketData
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     enet_ENetPacketHelper
 * Method:    setPacketData
 * Signature: (Lenet/ENetPacket;[BI)V
 */
JNIEXPORT void JNICALL Java_enet_ENetPacketHelper_setPacketData
  (JNIEnv *, jclass, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
