/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enet;

public class ENetChannel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetChannel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetChannel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ENetChannel obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetChannel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOutgoingReliableSequenceNumber(long value) {
    enetJNI.ENetChannel_outgoingReliableSequenceNumber_set(swigCPtr, this, value);
  }

  public long getOutgoingReliableSequenceNumber() {
    return enetJNI.ENetChannel_outgoingReliableSequenceNumber_get(swigCPtr, this);
  }

  public void setOutgoingUnreliableSequenceNumber(long value) {
    enetJNI.ENetChannel_outgoingUnreliableSequenceNumber_set(swigCPtr, this, value);
  }

  public long getOutgoingUnreliableSequenceNumber() {
    return enetJNI.ENetChannel_outgoingUnreliableSequenceNumber_get(swigCPtr, this);
  }

  public void setUsedReliableWindows(long value) {
    enetJNI.ENetChannel_usedReliableWindows_set(swigCPtr, this, value);
  }

  public long getUsedReliableWindows() {
    return enetJNI.ENetChannel_usedReliableWindows_get(swigCPtr, this);
  }

  public void setReliableWindows(SWIGTYPE_p_enet_uint16 value) {
    enetJNI.ENetChannel_reliableWindows_set(swigCPtr, this, SWIGTYPE_p_enet_uint16.getCPtr(value));
  }

  public SWIGTYPE_p_enet_uint16 getReliableWindows() {
    long cPtr = enetJNI.ENetChannel_reliableWindows_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_enet_uint16(cPtr, false);
  }

  public void setIncomingReliableSequenceNumber(long value) {
    enetJNI.ENetChannel_incomingReliableSequenceNumber_set(swigCPtr, this, value);
  }

  public long getIncomingReliableSequenceNumber() {
    return enetJNI.ENetChannel_incomingReliableSequenceNumber_get(swigCPtr, this);
  }

  public void setIncomingUnreliableSequenceNumber(long value) {
    enetJNI.ENetChannel_incomingUnreliableSequenceNumber_set(swigCPtr, this, value);
  }

  public long getIncomingUnreliableSequenceNumber() {
    return enetJNI.ENetChannel_incomingUnreliableSequenceNumber_get(swigCPtr, this);
  }

  public void setIncomingReliableCommands(SWIGTYPE_p_ENetList value) {
    enetJNI.ENetChannel_incomingReliableCommands_set(swigCPtr, this, SWIGTYPE_p_ENetList.getCPtr(value));
  }

  public SWIGTYPE_p_ENetList getIncomingReliableCommands() {
    return new SWIGTYPE_p_ENetList(enetJNI.ENetChannel_incomingReliableCommands_get(swigCPtr, this), true);
  }

  public void setIncomingUnreliableCommands(SWIGTYPE_p_ENetList value) {
    enetJNI.ENetChannel_incomingUnreliableCommands_set(swigCPtr, this, SWIGTYPE_p_ENetList.getCPtr(value));
  }

  public SWIGTYPE_p_ENetList getIncomingUnreliableCommands() {
    return new SWIGTYPE_p_ENetList(enetJNI.ENetChannel_incomingUnreliableCommands_get(swigCPtr, this), true);
  }

  public ENetChannel() {
    this(enetJNI.new_ENetChannel(), true);
  }

}
