/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enet;

public final class ENetSocketType {
  public final static ENetSocketType ENET_SOCKET_TYPE_STREAM = new ENetSocketType("ENET_SOCKET_TYPE_STREAM", enetJNI.ENET_SOCKET_TYPE_STREAM_get());
  public final static ENetSocketType ENET_SOCKET_TYPE_DATAGRAM = new ENetSocketType("ENET_SOCKET_TYPE_DATAGRAM", enetJNI.ENET_SOCKET_TYPE_DATAGRAM_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ENetSocketType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ENetSocketType.class + " with value " + swigValue);
  }

  private ENetSocketType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ENetSocketType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ENetSocketType(String swigName, ENetSocketType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ENetSocketType[] swigValues = { ENET_SOCKET_TYPE_STREAM, ENET_SOCKET_TYPE_DATAGRAM };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

