/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enet;

public class ENetAcknowledgement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetAcknowledgement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetAcknowledgement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ENetAcknowledgement obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetAcknowledgement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAcknowledgementList(SWIGTYPE_p_ENetListNode value) {
    enetJNI.ENetAcknowledgement_acknowledgementList_set(swigCPtr, this, SWIGTYPE_p_ENetListNode.getCPtr(value));
  }

  public SWIGTYPE_p_ENetListNode getAcknowledgementList() {
    return new SWIGTYPE_p_ENetListNode(enetJNI.ENetAcknowledgement_acknowledgementList_get(swigCPtr, this), true);
  }

  public void setSentTime(long value) {
    enetJNI.ENetAcknowledgement_sentTime_set(swigCPtr, this, value);
  }

  public long getSentTime() {
    return enetJNI.ENetAcknowledgement_sentTime_get(swigCPtr, this);
  }

  public void setCommand(SWIGTYPE_p_ENetProtocol value) {
    enetJNI.ENetAcknowledgement_command_set(swigCPtr, this, SWIGTYPE_p_ENetProtocol.getCPtr(value));
  }

  public SWIGTYPE_p_ENetProtocol getCommand() {
    return new SWIGTYPE_p_ENetProtocol(enetJNI.ENetAcknowledgement_command_get(swigCPtr, this), true);
  }

  public ENetAcknowledgement() {
    this(enetJNI.new_ENetAcknowledgement(), true);
  }

}
