/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enet;

public final class ENetPacketFlag {
  public final static ENetPacketFlag ENET_PACKET_FLAG_RELIABLE = new ENetPacketFlag("ENET_PACKET_FLAG_RELIABLE", enetJNI.ENET_PACKET_FLAG_RELIABLE_get());
  public final static ENetPacketFlag ENET_PACKET_FLAG_UNSEQUENCED = new ENetPacketFlag("ENET_PACKET_FLAG_UNSEQUENCED", enetJNI.ENET_PACKET_FLAG_UNSEQUENCED_get());
  public final static ENetPacketFlag ENET_PACKET_FLAG_NO_ALLOCATE = new ENetPacketFlag("ENET_PACKET_FLAG_NO_ALLOCATE", enetJNI.ENET_PACKET_FLAG_NO_ALLOCATE_get());
  public final static ENetPacketFlag ENET_PACKET_FLAG_UNRELIABLE_FRAGMENT = new ENetPacketFlag("ENET_PACKET_FLAG_UNRELIABLE_FRAGMENT", enetJNI.ENET_PACKET_FLAG_UNRELIABLE_FRAGMENT_get());
  public final static ENetPacketFlag ENET_PACKET_FLAG_SENT = new ENetPacketFlag("ENET_PACKET_FLAG_SENT", enetJNI.ENET_PACKET_FLAG_SENT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ENetPacketFlag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ENetPacketFlag.class + " with value " + swigValue);
  }

  private ENetPacketFlag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ENetPacketFlag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ENetPacketFlag(String swigName, ENetPacketFlag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ENetPacketFlag[] swigValues = { ENET_PACKET_FLAG_RELIABLE, ENET_PACKET_FLAG_UNSEQUENCED, ENET_PACKET_FLAG_NO_ALLOCATE, ENET_PACKET_FLAG_UNRELIABLE_FRAGMENT, ENET_PACKET_FLAG_SENT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

