/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enet;

public final class ENetPeerState {
  public final static ENetPeerState ENET_PEER_STATE_DISCONNECTED = new ENetPeerState("ENET_PEER_STATE_DISCONNECTED", enetJNI.ENET_PEER_STATE_DISCONNECTED_get());
  public final static ENetPeerState ENET_PEER_STATE_CONNECTING = new ENetPeerState("ENET_PEER_STATE_CONNECTING", enetJNI.ENET_PEER_STATE_CONNECTING_get());
  public final static ENetPeerState ENET_PEER_STATE_ACKNOWLEDGING_CONNECT = new ENetPeerState("ENET_PEER_STATE_ACKNOWLEDGING_CONNECT", enetJNI.ENET_PEER_STATE_ACKNOWLEDGING_CONNECT_get());
  public final static ENetPeerState ENET_PEER_STATE_CONNECTION_PENDING = new ENetPeerState("ENET_PEER_STATE_CONNECTION_PENDING", enetJNI.ENET_PEER_STATE_CONNECTION_PENDING_get());
  public final static ENetPeerState ENET_PEER_STATE_CONNECTION_SUCCEEDED = new ENetPeerState("ENET_PEER_STATE_CONNECTION_SUCCEEDED", enetJNI.ENET_PEER_STATE_CONNECTION_SUCCEEDED_get());
  public final static ENetPeerState ENET_PEER_STATE_CONNECTED = new ENetPeerState("ENET_PEER_STATE_CONNECTED", enetJNI.ENET_PEER_STATE_CONNECTED_get());
  public final static ENetPeerState ENET_PEER_STATE_DISCONNECT_LATER = new ENetPeerState("ENET_PEER_STATE_DISCONNECT_LATER", enetJNI.ENET_PEER_STATE_DISCONNECT_LATER_get());
  public final static ENetPeerState ENET_PEER_STATE_DISCONNECTING = new ENetPeerState("ENET_PEER_STATE_DISCONNECTING", enetJNI.ENET_PEER_STATE_DISCONNECTING_get());
  public final static ENetPeerState ENET_PEER_STATE_ACKNOWLEDGING_DISCONNECT = new ENetPeerState("ENET_PEER_STATE_ACKNOWLEDGING_DISCONNECT", enetJNI.ENET_PEER_STATE_ACKNOWLEDGING_DISCONNECT_get());
  public final static ENetPeerState ENET_PEER_STATE_ZOMBIE = new ENetPeerState("ENET_PEER_STATE_ZOMBIE", enetJNI.ENET_PEER_STATE_ZOMBIE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ENetPeerState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ENetPeerState.class + " with value " + swigValue);
  }

  private ENetPeerState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ENetPeerState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ENetPeerState(String swigName, ENetPeerState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ENetPeerState[] swigValues = { ENET_PEER_STATE_DISCONNECTED, ENET_PEER_STATE_CONNECTING, ENET_PEER_STATE_ACKNOWLEDGING_CONNECT, ENET_PEER_STATE_CONNECTION_PENDING, ENET_PEER_STATE_CONNECTION_SUCCEEDED, ENET_PEER_STATE_CONNECTED, ENET_PEER_STATE_DISCONNECT_LATER, ENET_PEER_STATE_DISCONNECTING, ENET_PEER_STATE_ACKNOWLEDGING_DISCONNECT, ENET_PEER_STATE_ZOMBIE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

