/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enet;

public class ENetHost {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetHost(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetHost obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ENetHost obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetHost(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSocket(SWIGTYPE_p_ENetSocket value) {
    enetJNI.ENetHost_socket_set(swigCPtr, this, SWIGTYPE_p_ENetSocket.getCPtr(value));
  }

  public SWIGTYPE_p_ENetSocket getSocket() {
    return new SWIGTYPE_p_ENetSocket(enetJNI.ENetHost_socket_get(swigCPtr, this), true);
  }

  public void setAddress(ENetAddress value) {
    enetJNI.ENetHost_address_set(swigCPtr, this, ENetAddress.getCPtr(value), value);
  }

  public ENetAddress getAddress() {
    long cPtr = enetJNI.ENetHost_address_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetAddress(cPtr, false);
  }

  public void setIncomingBandwidth(long value) {
    enetJNI.ENetHost_incomingBandwidth_set(swigCPtr, this, value);
  }

  public long getIncomingBandwidth() {
    return enetJNI.ENetHost_incomingBandwidth_get(swigCPtr, this);
  }

  public void setOutgoingBandwidth(long value) {
    enetJNI.ENetHost_outgoingBandwidth_set(swigCPtr, this, value);
  }

  public long getOutgoingBandwidth() {
    return enetJNI.ENetHost_outgoingBandwidth_get(swigCPtr, this);
  }

  public void setBandwidthThrottleEpoch(long value) {
    enetJNI.ENetHost_bandwidthThrottleEpoch_set(swigCPtr, this, value);
  }

  public long getBandwidthThrottleEpoch() {
    return enetJNI.ENetHost_bandwidthThrottleEpoch_get(swigCPtr, this);
  }

  public void setMtu(long value) {
    enetJNI.ENetHost_mtu_set(swigCPtr, this, value);
  }

  public long getMtu() {
    return enetJNI.ENetHost_mtu_get(swigCPtr, this);
  }

  public void setRandomSeed(long value) {
    enetJNI.ENetHost_randomSeed_set(swigCPtr, this, value);
  }

  public long getRandomSeed() {
    return enetJNI.ENetHost_randomSeed_get(swigCPtr, this);
  }

  public void setRecalculateBandwidthLimits(int value) {
    enetJNI.ENetHost_recalculateBandwidthLimits_set(swigCPtr, this, value);
  }

  public int getRecalculateBandwidthLimits() {
    return enetJNI.ENetHost_recalculateBandwidthLimits_get(swigCPtr, this);
  }

  public void setPeers(ENetPeer value) {
    enetJNI.ENetHost_peers_set(swigCPtr, this, ENetPeer.getCPtr(value), value);
  }

  public ENetPeer getPeers() {
    long cPtr = enetJNI.ENetHost_peers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetPeer(cPtr, false);
  }

  public void setPeerCount(long value) {
    enetJNI.ENetHost_peerCount_set(swigCPtr, this, value);
  }

  public long getPeerCount() {
    return enetJNI.ENetHost_peerCount_get(swigCPtr, this);
  }

  public void setChannelLimit(long value) {
    enetJNI.ENetHost_channelLimit_set(swigCPtr, this, value);
  }

  public long getChannelLimit() {
    return enetJNI.ENetHost_channelLimit_get(swigCPtr, this);
  }

  public void setServiceTime(long value) {
    enetJNI.ENetHost_serviceTime_set(swigCPtr, this, value);
  }

  public long getServiceTime() {
    return enetJNI.ENetHost_serviceTime_get(swigCPtr, this);
  }

  public void setDispatchQueue(SWIGTYPE_p_ENetList value) {
    enetJNI.ENetHost_dispatchQueue_set(swigCPtr, this, SWIGTYPE_p_ENetList.getCPtr(value));
  }

  public SWIGTYPE_p_ENetList getDispatchQueue() {
    return new SWIGTYPE_p_ENetList(enetJNI.ENetHost_dispatchQueue_get(swigCPtr, this), true);
  }

  public void setTotalQueued(long value) {
    enetJNI.ENetHost_totalQueued_set(swigCPtr, this, value);
  }

  public long getTotalQueued() {
    return enetJNI.ENetHost_totalQueued_get(swigCPtr, this);
  }

  public void setPacketSize(long value) {
    enetJNI.ENetHost_packetSize_set(swigCPtr, this, value);
  }

  public long getPacketSize() {
    return enetJNI.ENetHost_packetSize_get(swigCPtr, this);
  }

  public void setHeaderFlags(long value) {
    enetJNI.ENetHost_headerFlags_set(swigCPtr, this, value);
  }

  public long getHeaderFlags() {
    return enetJNI.ENetHost_headerFlags_get(swigCPtr, this);
  }

  public void setCommands(SWIGTYPE_p_ENetProtocol value) {
    enetJNI.ENetHost_commands_set(swigCPtr, this, SWIGTYPE_p_ENetProtocol.getCPtr(value));
  }

  public SWIGTYPE_p_ENetProtocol getCommands() {
    long cPtr = enetJNI.ENetHost_commands_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ENetProtocol(cPtr, false);
  }

  public void setCommandCount(long value) {
    enetJNI.ENetHost_commandCount_set(swigCPtr, this, value);
  }

  public long getCommandCount() {
    return enetJNI.ENetHost_commandCount_get(swigCPtr, this);
  }

  public void setBuffers(SWIGTYPE_p_ENetBuffer value) {
    enetJNI.ENetHost_buffers_set(swigCPtr, this, SWIGTYPE_p_ENetBuffer.getCPtr(value));
  }

  public SWIGTYPE_p_ENetBuffer getBuffers() {
    long cPtr = enetJNI.ENetHost_buffers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ENetBuffer(cPtr, false);
  }

  public void setBufferCount(long value) {
    enetJNI.ENetHost_bufferCount_set(swigCPtr, this, value);
  }

  public long getBufferCount() {
    return enetJNI.ENetHost_bufferCount_get(swigCPtr, this);
  }

  public void setChecksum(SWIGTYPE_p_f_p_q_const__ENetBuffer_size_t__enet_uint32 value) {
    enetJNI.ENetHost_checksum_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__ENetBuffer_size_t__enet_uint32.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__ENetBuffer_size_t__enet_uint32 getChecksum() {
    long cPtr = enetJNI.ENetHost_checksum_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__ENetBuffer_size_t__enet_uint32(cPtr, false);
  }

  public void setCompressor(ENetCompressor value) {
    enetJNI.ENetHost_compressor_set(swigCPtr, this, ENetCompressor.getCPtr(value), value);
  }

  public ENetCompressor getCompressor() {
    long cPtr = enetJNI.ENetHost_compressor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetCompressor(cPtr, false);
  }

  public void setPacketData(SWIGTYPE_p_a_ENET_PROTOCOL_MAXIMUM_MTU__enet_uint8 value) {
    enetJNI.ENetHost_packetData_set(swigCPtr, this, SWIGTYPE_p_a_ENET_PROTOCOL_MAXIMUM_MTU__enet_uint8.getCPtr(value));
  }

  public SWIGTYPE_p_a_ENET_PROTOCOL_MAXIMUM_MTU__enet_uint8 getPacketData() {
    long cPtr = enetJNI.ENetHost_packetData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_ENET_PROTOCOL_MAXIMUM_MTU__enet_uint8(cPtr, false);
  }

  public void setReceivedAddress(ENetAddress value) {
    enetJNI.ENetHost_receivedAddress_set(swigCPtr, this, ENetAddress.getCPtr(value), value);
  }

  public ENetAddress getReceivedAddress() {
    long cPtr = enetJNI.ENetHost_receivedAddress_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetAddress(cPtr, false);
  }

  public void setReceivedData(SWIGTYPE_p_enet_uint8 value) {
    enetJNI.ENetHost_receivedData_set(swigCPtr, this, SWIGTYPE_p_enet_uint8.getCPtr(value));
  }

  public SWIGTYPE_p_enet_uint8 getReceivedData() {
    long cPtr = enetJNI.ENetHost_receivedData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_enet_uint8(cPtr, false);
  }

  public void setReceivedDataLength(long value) {
    enetJNI.ENetHost_receivedDataLength_set(swigCPtr, this, value);
  }

  public long getReceivedDataLength() {
    return enetJNI.ENetHost_receivedDataLength_get(swigCPtr, this);
  }

  public void setTotalSentData(long value) {
    enetJNI.ENetHost_totalSentData_set(swigCPtr, this, value);
  }

  public long getTotalSentData() {
    return enetJNI.ENetHost_totalSentData_get(swigCPtr, this);
  }

  public void setTotalSentPackets(long value) {
    enetJNI.ENetHost_totalSentPackets_set(swigCPtr, this, value);
  }

  public long getTotalSentPackets() {
    return enetJNI.ENetHost_totalSentPackets_get(swigCPtr, this);
  }

  public void setTotalReceivedData(long value) {
    enetJNI.ENetHost_totalReceivedData_set(swigCPtr, this, value);
  }

  public long getTotalReceivedData() {
    return enetJNI.ENetHost_totalReceivedData_get(swigCPtr, this);
  }

  public void setTotalReceivedPackets(long value) {
    enetJNI.ENetHost_totalReceivedPackets_set(swigCPtr, this, value);
  }

  public long getTotalReceivedPackets() {
    return enetJNI.ENetHost_totalReceivedPackets_get(swigCPtr, this);
  }

  public void setIntercept(SWIGTYPE_p_f_p__ENetHost_p__ENetEvent__int value) {
    enetJNI.ENetHost_intercept_set(swigCPtr, this, SWIGTYPE_p_f_p__ENetHost_p__ENetEvent__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__ENetHost_p__ENetEvent__int getIntercept() {
    long cPtr = enetJNI.ENetHost_intercept_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__ENetHost_p__ENetEvent__int(cPtr, false);
  }

  public void setConnectedPeers(long value) {
    enetJNI.ENetHost_connectedPeers_set(swigCPtr, this, value);
  }

  public long getConnectedPeers() {
    return enetJNI.ENetHost_connectedPeers_get(swigCPtr, this);
  }

  public void setBandwidthLimitedPeers(long value) {
    enetJNI.ENetHost_bandwidthLimitedPeers_set(swigCPtr, this, value);
  }

  public long getBandwidthLimitedPeers() {
    return enetJNI.ENetHost_bandwidthLimitedPeers_get(swigCPtr, this);
  }

  public void setDuplicatePeers(long value) {
    enetJNI.ENetHost_duplicatePeers_set(swigCPtr, this, value);
  }

  public long getDuplicatePeers() {
    return enetJNI.ENetHost_duplicatePeers_get(swigCPtr, this);
  }

  public void setMaximumPacketSize(long value) {
    enetJNI.ENetHost_maximumPacketSize_set(swigCPtr, this, value);
  }

  public long getMaximumPacketSize() {
    return enetJNI.ENetHost_maximumPacketSize_get(swigCPtr, this);
  }

  public void setMaximumWaitingData(long value) {
    enetJNI.ENetHost_maximumWaitingData_set(swigCPtr, this, value);
  }

  public long getMaximumWaitingData() {
    return enetJNI.ENetHost_maximumWaitingData_get(swigCPtr, this);
  }

  public ENetHost() {
    this(enetJNI.new_ENetHost(), true);
  }

}
