/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enet;

public final class ENetEventType {
  public final static ENetEventType ENET_EVENT_TYPE_NONE = new ENetEventType("ENET_EVENT_TYPE_NONE", enetJNI.ENET_EVENT_TYPE_NONE_get());
  public final static ENetEventType ENET_EVENT_TYPE_CONNECT = new ENetEventType("ENET_EVENT_TYPE_CONNECT", enetJNI.ENET_EVENT_TYPE_CONNECT_get());
  public final static ENetEventType ENET_EVENT_TYPE_DISCONNECT = new ENetEventType("ENET_EVENT_TYPE_DISCONNECT", enetJNI.ENET_EVENT_TYPE_DISCONNECT_get());
  public final static ENetEventType ENET_EVENT_TYPE_RECEIVE = new ENetEventType("ENET_EVENT_TYPE_RECEIVE", enetJNI.ENET_EVENT_TYPE_RECEIVE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ENetEventType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ENetEventType.class + " with value " + swigValue);
  }

  private ENetEventType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ENetEventType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ENetEventType(String swigName, ENetEventType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ENetEventType[] swigValues = { ENET_EVENT_TYPE_NONE, ENET_EVENT_TYPE_CONNECT, ENET_EVENT_TYPE_DISCONNECT, ENET_EVENT_TYPE_RECEIVE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

