/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enet;

public final class ENetSocketShutdown {
  public final static ENetSocketShutdown ENET_SOCKET_SHUTDOWN_READ = new ENetSocketShutdown("ENET_SOCKET_SHUTDOWN_READ", enetJNI.ENET_SOCKET_SHUTDOWN_READ_get());
  public final static ENetSocketShutdown ENET_SOCKET_SHUTDOWN_WRITE = new ENetSocketShutdown("ENET_SOCKET_SHUTDOWN_WRITE", enetJNI.ENET_SOCKET_SHUTDOWN_WRITE_get());
  public final static ENetSocketShutdown ENET_SOCKET_SHUTDOWN_READ_WRITE = new ENetSocketShutdown("ENET_SOCKET_SHUTDOWN_READ_WRITE", enetJNI.ENET_SOCKET_SHUTDOWN_READ_WRITE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ENetSocketShutdown swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ENetSocketShutdown.class + " with value " + swigValue);
  }

  private ENetSocketShutdown(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ENetSocketShutdown(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ENetSocketShutdown(String swigName, ENetSocketShutdown swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ENetSocketShutdown[] swigValues = { ENET_SOCKET_SHUTDOWN_READ, ENET_SOCKET_SHUTDOWN_WRITE, ENET_SOCKET_SHUTDOWN_READ_WRITE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

