/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enet;

public final class ENetPeerFlag {
  public final static ENetPeerFlag ENET_PEER_FLAG_NEEDS_DISPATCH = new ENetPeerFlag("ENET_PEER_FLAG_NEEDS_DISPATCH", enetJNI.ENET_PEER_FLAG_NEEDS_DISPATCH_get());
  public final static ENetPeerFlag ENET_PEER_FLAG_CONTINUE_SENDING = new ENetPeerFlag("ENET_PEER_FLAG_CONTINUE_SENDING", enetJNI.ENET_PEER_FLAG_CONTINUE_SENDING_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ENetPeerFlag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ENetPeerFlag.class + " with value " + swigValue);
  }

  private ENetPeerFlag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ENetPeerFlag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ENetPeerFlag(String swigName, ENetPeerFlag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ENetPeerFlag[] swigValues = { ENET_PEER_FLAG_NEEDS_DISPATCH, ENET_PEER_FLAG_CONTINUE_SENDING };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

