/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enet;

public class ENetAddress {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetAddress(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetAddress obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ENetAddress obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetAddress(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHost(long value) {
    enetJNI.ENetAddress_host_set(swigCPtr, this, value);
  }

  public long getHost() {
    return enetJNI.ENetAddress_host_get(swigCPtr, this);
  }

  public void setPort(long value) {
    enetJNI.ENetAddress_port_set(swigCPtr, this, value);
  }

  public long getPort() {
    return enetJNI.ENetAddress_port_get(swigCPtr, this);
  }

  public ENetAddress() {
    this(enetJNI.new_ENetAddress(), true);
  }

}
