/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package enet;

public class ENetIncomingCommand {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetIncomingCommand(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetIncomingCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ENetIncomingCommand obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetIncomingCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIncomingCommandList(SWIGTYPE_p_ENetListNode value) {
    enetJNI.ENetIncomingCommand_incomingCommandList_set(swigCPtr, this, SWIGTYPE_p_ENetListNode.getCPtr(value));
  }

  public SWIGTYPE_p_ENetListNode getIncomingCommandList() {
    return new SWIGTYPE_p_ENetListNode(enetJNI.ENetIncomingCommand_incomingCommandList_get(swigCPtr, this), true);
  }

  public void setReliableSequenceNumber(long value) {
    enetJNI.ENetIncomingCommand_reliableSequenceNumber_set(swigCPtr, this, value);
  }

  public long getReliableSequenceNumber() {
    return enetJNI.ENetIncomingCommand_reliableSequenceNumber_get(swigCPtr, this);
  }

  public void setUnreliableSequenceNumber(long value) {
    enetJNI.ENetIncomingCommand_unreliableSequenceNumber_set(swigCPtr, this, value);
  }

  public long getUnreliableSequenceNumber() {
    return enetJNI.ENetIncomingCommand_unreliableSequenceNumber_get(swigCPtr, this);
  }

  public void setCommand(SWIGTYPE_p_ENetProtocol value) {
    enetJNI.ENetIncomingCommand_command_set(swigCPtr, this, SWIGTYPE_p_ENetProtocol.getCPtr(value));
  }

  public SWIGTYPE_p_ENetProtocol getCommand() {
    return new SWIGTYPE_p_ENetProtocol(enetJNI.ENetIncomingCommand_command_get(swigCPtr, this), true);
  }

  public void setFragmentCount(long value) {
    enetJNI.ENetIncomingCommand_fragmentCount_set(swigCPtr, this, value);
  }

  public long getFragmentCount() {
    return enetJNI.ENetIncomingCommand_fragmentCount_get(swigCPtr, this);
  }

  public void setFragmentsRemaining(long value) {
    enetJNI.ENetIncomingCommand_fragmentsRemaining_set(swigCPtr, this, value);
  }

  public long getFragmentsRemaining() {
    return enetJNI.ENetIncomingCommand_fragmentsRemaining_get(swigCPtr, this);
  }

  public void setFragments(SWIGTYPE_p_enet_uint32 value) {
    enetJNI.ENetIncomingCommand_fragments_set(swigCPtr, this, SWIGTYPE_p_enet_uint32.getCPtr(value));
  }

  public SWIGTYPE_p_enet_uint32 getFragments() {
    long cPtr = enetJNI.ENetIncomingCommand_fragments_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_enet_uint32(cPtr, false);
  }

  public void setPacket(ENetPacket value) {
    enetJNI.ENetIncomingCommand_packet_set(swigCPtr, this, ENetPacket.getCPtr(value), value);
  }

  public ENetPacket getPacket() {
    long cPtr = enetJNI.ENetIncomingCommand_packet_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetPacket(cPtr, false);
  }

  public ENetIncomingCommand() {
    this(enetJNI.new_ENetIncomingCommand(), true);
  }

}
